kind: pipeline
type: docker
name: default
   
steps:
- name: production-deployment
  image: docker
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock
  commands:
  - docker build -t test_build .

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock