
version: "3"

services:
  web:
    image: express_prod
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ~/app/src/config.js:/var/www/express/config.js
      - ~/app/src/build:/var/www/express/build
      # mount the images folder
      - ~/app/public:/var/www/express/public
  worker:
    image: matchstick-worker
    volumes:
      - ~/app/src/config.js:/app/config.js
  postgresDB:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
      external: true