# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t express_prod .
      - run:
          name: Add matchstick to known hosts
          command: ssh-keyscan -H 45.32.225.95 >> ~/.ssh/known_hosts     
      - run:
           name: Deploy Over SSH
           command: |
             rsync -cave ssh $SSH_USER@$SSH_HOST:/app/src 

