# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.0

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:
      - run: 
          name: Install pv to monitor transfer
          command: apk update && apk add pv
          
      - add_ssh_keys:
          fingerprints:
            - "de:47:55:2a:77:39:a0:71:e7:a7:d3:4c:84:45:c8:51"
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t express_prod .

      - run:
          name: Add matchstick to known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts     
      - run:
           name: Deploy Over SSH, Using Docker save and load on remote machine
           command: |
             docker save express_prod | pv | ssh -C $SSH_USER@$SSH_HOST docker load

