# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.0

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:
          
      - add_ssh_keys:
          fingerprints:
            - "ec:f5:0e:a9:d3:1b:6a:2f:37:fb:cd:e4:17:b7:68:ad"
            
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t express_prod .

      - run:
          name: Add matchstick to known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts  

      - run:
          name: Save the docker image as a tar file
          command: |
            docker save express_prod | gzip > /express_prod.tar.gz 
            
      - run:
           name: Deploy Over SCP
           command: |
             scp /express_prod.tar.gz $SSH_USER@$SSH_HOST:/app/src 

      - run:
           name: Move Docker Compose file to remote, should be a better way to deploy compose files
           command: |
             scp /project/docker-compose.yml $SSH_USER@$SSH_HOST:/app 

      - run:
           name: Load into Docker in remote
           command: |
             ssh $SSH_USER@$SSH_HOST  'docker load < /app/src/express_prod.tar.gz'



