# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.0

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small
    steps:
          
      - add_ssh_keys:
          fingerprints:
            - "de:47:55:2a:77:39:a0:71:e7:a7:d3:4c:84:45:c8:51"
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t express_prod .

      - run:
          name: Add matchstick to known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts  

      - run:
          name: Save the docker image as a tar file
          command: |
            docker save express_prod | gzip > /express_prod.tar.gz 
      - run:
           name: Deploy Over SCP
           command: |
             scp /express_prod.tar.gz $SSH_USER@$SSH_HOST:/app/src 

      - run:
           name: Load into Docker in remote
           command: |
             ssh $SSH_USER@$SSH_HOST && doocker load < /app/src/express_prod.tar.gz



